#Printer Parter 
p_name: Parter_60.12_22
p_ip: 192.168.60.12
p_port_nr: 9100
p_port_name: Parter_60_12_22
p_driver_path: \\dc01\MSI\Develop257i\Polish\Drivers\PCL6\Win_x64
p_inf_name: KOAXGJ__.inf
p_driver_name: KONICA MINOLTA C360iSeriesPCL
  

